# Generated by Django 3.0.3 on 2021-02-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_bookingapartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingapartment',
            old_name='room_no',
            new_name='apartment_no',
        ),
    ]
