# Generated by Django 3.0.3 on 2021-02-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200314_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='roommanager',
            name='gender',
        ),
    ]
